########################################
# NETWORK
########################################

bind 0.0.0.0
port 6379
protected-mode yes

########################################
# SECURITY
########################################

requirepass supersecretredispassword

########################################
# PERSISTENCE
########################################

appendonly yes
appendfsync everysec

save 900 1
save 300 10
save 60 10000

########################################
# MEMORY
########################################

maxmemory 1gb
maxmemory-policy allkeys-lru

########################################
# LOGGING
########################################

loglevel notice

########################################
# PERFORMANCE
########################################

tcp-keepalive 300
timeout 0

########################################
# DATA
########################################

dir /data