apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mp-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/gaganpreet-s1ngh/marketing-platform-frontend:latest
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "production"
          ports:
            - containerPort: 3010
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 3010
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3010
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mp-prod
spec:
  selector:
    app: frontend
  ports:
    - port: 3010
      targetPort: 3010
  type: ClusterIP
